trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet --info
  displayName: '[Server] dotnet --info'

- script: dotnet restore
  displayName: '[Server] dotnet restore'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: '[Server] dotnet build $(buildConfiguration)'
