/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v12.3.1.0 (NJsonSchema v9.14.1.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming



export class BaseDataTransfersOfAccountAndAccountSimpleResponse implements IBaseDataTransfersOfAccountAndAccountSimpleResponse {

    constructor(data?: IBaseDataTransfersOfAccountAndAccountSimpleResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
    }

    static fromJS(data: any): BaseDataTransfersOfAccountAndAccountSimpleResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BaseDataTransfersOfAccountAndAccountSimpleResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IBaseDataTransfersOfAccountAndAccountSimpleResponse {
}

export class AccountSimpleResponse extends BaseDataTransfersOfAccountAndAccountSimpleResponse implements IAccountSimpleResponse {
    id!: number;
    name!: string;
    email!: string;
    picture!: string;
    access!: EnumAccess;

    constructor(data?: IAccountSimpleResponse) {
        super(data);
    }

    init(data?: any) {
        super.init(data);
        if (data) {
            this.id = data["id"] !== undefined ? data["id"] : <any>null;
            this.name = data["name"] !== undefined ? data["name"] : <any>null;
            this.email = data["email"] !== undefined ? data["email"] : <any>null;
            this.picture = data["picture"] !== undefined ? data["picture"] : <any>null;
            this.access = data["access"] !== undefined ? data["access"] : <any>null;
        }
    }

    static fromJS(data: any): AccountSimpleResponse {
        data = typeof data === 'object' ? data : {};
        let result = new AccountSimpleResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id !== undefined ? this.id : <any>null;
        data["name"] = this.name !== undefined ? this.name : <any>null;
        data["email"] = this.email !== undefined ? this.email : <any>null;
        data["picture"] = this.picture !== undefined ? this.picture : <any>null;
        data["access"] = this.access !== undefined ? this.access : <any>null;
        super.toJSON(data);
        return data; 
    }
}

export interface IAccountSimpleResponse extends IBaseDataTransfersOfAccountAndAccountSimpleResponse {
    id: number;
    name: string;
    email: string;
    picture: string;
    access: EnumAccess;
}

export enum EnumAccess {
    Administrator = "Administrator", 
    Moderator = "Moderator", 
    NormalUser = "NormalUser", 
    BannedUser = "BannedUser", 
}

export class ErrorResponse implements IErrorResponse {
    action?: string | null;
    description?: string | null;
    model?: string | null;

    constructor(data?: IErrorResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.action = data["action"] !== undefined ? data["action"] : <any>null;
            this.description = data["description"] !== undefined ? data["description"] : <any>null;
            this.model = data["model"] !== undefined ? data["model"] : <any>null;
        }
    }

    static fromJS(data: any): ErrorResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ErrorResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["action"] = this.action !== undefined ? this.action : <any>null;
        data["description"] = this.description !== undefined ? this.description : <any>null;
        data["model"] = this.model !== undefined ? this.model : <any>null;
        return data; 
    }
}

export interface IErrorResponse {
    action?: string | null;
    description?: string | null;
    model?: string | null;
}

export class BaseDataTransfersOfAccountAndAccountResponse implements IBaseDataTransfersOfAccountAndAccountResponse {

    constructor(data?: IBaseDataTransfersOfAccountAndAccountResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
    }

    static fromJS(data: any): BaseDataTransfersOfAccountAndAccountResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BaseDataTransfersOfAccountAndAccountResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IBaseDataTransfersOfAccountAndAccountResponse {
}

export class AccountResponse extends BaseDataTransfersOfAccountAndAccountResponse implements IAccountResponse {
    id!: number;
    name!: string;
    email!: string;
    picture!: string;
    access!: EnumAccess;
    gender!: EnumGender;
    joined!: string;

    constructor(data?: IAccountResponse) {
        super(data);
    }

    init(data?: any) {
        super.init(data);
        if (data) {
            this.id = data["id"] !== undefined ? data["id"] : <any>null;
            this.name = data["name"] !== undefined ? data["name"] : <any>null;
            this.email = data["email"] !== undefined ? data["email"] : <any>null;
            this.picture = data["picture"] !== undefined ? data["picture"] : <any>null;
            this.access = data["access"] !== undefined ? data["access"] : <any>null;
            this.gender = data["gender"] !== undefined ? data["gender"] : <any>null;
            this.joined = data["joined"] !== undefined ? data["joined"] : <any>null;
        }
    }

    static fromJS(data: any): AccountResponse {
        data = typeof data === 'object' ? data : {};
        let result = new AccountResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id !== undefined ? this.id : <any>null;
        data["name"] = this.name !== undefined ? this.name : <any>null;
        data["email"] = this.email !== undefined ? this.email : <any>null;
        data["picture"] = this.picture !== undefined ? this.picture : <any>null;
        data["access"] = this.access !== undefined ? this.access : <any>null;
        data["gender"] = this.gender !== undefined ? this.gender : <any>null;
        data["joined"] = this.joined !== undefined ? this.joined : <any>null;
        super.toJSON(data);
        return data; 
    }
}

export interface IAccountResponse extends IBaseDataTransfersOfAccountAndAccountResponse {
    id: number;
    name: string;
    email: string;
    picture: string;
    access: EnumAccess;
    gender: EnumGender;
    joined: string;
}

export enum EnumGender {
    Male = "Male", 
    Female = "Female", 
    Unknown = "Unknown", 
}

export class AccountChangePasswordRequest implements IAccountChangePasswordRequest {
    password!: string;
    newPassword!: string;

    constructor(data?: IAccountChangePasswordRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.password = data["password"] !== undefined ? data["password"] : <any>null;
            this.newPassword = data["newPassword"] !== undefined ? data["newPassword"] : <any>null;
        }
    }

    static fromJS(data: any): AccountChangePasswordRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AccountChangePasswordRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["password"] = this.password !== undefined ? this.password : <any>null;
        data["newPassword"] = this.newPassword !== undefined ? this.newPassword : <any>null;
        return data; 
    }
}

export interface IAccountChangePasswordRequest {
    password: string;
    newPassword: string;
}

export class BaseDataTransfersOfAccountAndAccountUpdateRequest implements IBaseDataTransfersOfAccountAndAccountUpdateRequest {

    constructor(data?: IBaseDataTransfersOfAccountAndAccountUpdateRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
    }

    static fromJS(data: any): BaseDataTransfersOfAccountAndAccountUpdateRequest {
        data = typeof data === 'object' ? data : {};
        let result = new BaseDataTransfersOfAccountAndAccountUpdateRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IBaseDataTransfersOfAccountAndAccountUpdateRequest {
}

export class AccountUpdateRequest extends BaseDataTransfersOfAccountAndAccountUpdateRequest implements IAccountUpdateRequest {
    name!: string;
    picture!: string;
    gender!: EnumGender;

    constructor(data?: IAccountUpdateRequest) {
        super(data);
    }

    init(data?: any) {
        super.init(data);
        if (data) {
            this.name = data["name"] !== undefined ? data["name"] : <any>null;
            this.picture = data["picture"] !== undefined ? data["picture"] : <any>null;
            this.gender = data["gender"] !== undefined ? data["gender"] : <any>null;
        }
    }

    static fromJS(data: any): AccountUpdateRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AccountUpdateRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name !== undefined ? this.name : <any>null;
        data["picture"] = this.picture !== undefined ? this.picture : <any>null;
        data["gender"] = this.gender !== undefined ? this.gender : <any>null;
        super.toJSON(data);
        return data; 
    }
}

export interface IAccountUpdateRequest extends IBaseDataTransfersOfAccountAndAccountUpdateRequest {
    name: string;
    picture: string;
    gender: EnumGender;
}

export class AccountUpdateAccessRequest implements IAccountUpdateAccessRequest {
    account!: AccountIdTransfer;
    access!: EnumAccess;

    constructor(data?: IAccountUpdateAccessRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.account = new AccountIdTransfer();
        }
    }

    init(data?: any) {
        if (data) {
            this.account = data["account"] ? AccountIdTransfer.fromJS(data["account"]) : new AccountIdTransfer();
            this.access = data["access"] !== undefined ? data["access"] : <any>null;
        }
    }

    static fromJS(data: any): AccountUpdateAccessRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AccountUpdateAccessRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["account"] = this.account ? this.account.toJSON() : <any>null;
        data["access"] = this.access !== undefined ? this.access : <any>null;
        return data; 
    }
}

export interface IAccountUpdateAccessRequest {
    account: AccountIdTransfer;
    access: EnumAccess;
}

export class BaseDataTransfersOfAccountAndAccountIdTransfer implements IBaseDataTransfersOfAccountAndAccountIdTransfer {

    constructor(data?: IBaseDataTransfersOfAccountAndAccountIdTransfer) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
    }

    static fromJS(data: any): BaseDataTransfersOfAccountAndAccountIdTransfer {
        data = typeof data === 'object' ? data : {};
        let result = new BaseDataTransfersOfAccountAndAccountIdTransfer();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IBaseDataTransfersOfAccountAndAccountIdTransfer {
}

export class AccountIdTransfer extends BaseDataTransfersOfAccountAndAccountIdTransfer implements IAccountIdTransfer {
    id!: number;

    constructor(data?: IAccountIdTransfer) {
        super(data);
    }

    init(data?: any) {
        super.init(data);
        if (data) {
            this.id = data["id"] !== undefined ? data["id"] : <any>null;
        }
    }

    static fromJS(data: any): AccountIdTransfer {
        data = typeof data === 'object' ? data : {};
        let result = new AccountIdTransfer();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id !== undefined ? this.id : <any>null;
        super.toJSON(data);
        return data; 
    }
}

export interface IAccountIdTransfer extends IBaseDataTransfersOfAccountAndAccountIdTransfer {
    id: number;
}

export class BaseDataTransfersOfAccountAndAccountCreateRequest implements IBaseDataTransfersOfAccountAndAccountCreateRequest {

    constructor(data?: IBaseDataTransfersOfAccountAndAccountCreateRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
    }

    static fromJS(data: any): BaseDataTransfersOfAccountAndAccountCreateRequest {
        data = typeof data === 'object' ? data : {};
        let result = new BaseDataTransfersOfAccountAndAccountCreateRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IBaseDataTransfersOfAccountAndAccountCreateRequest {
}

export class AccountCreateRequest extends BaseDataTransfersOfAccountAndAccountCreateRequest implements IAccountCreateRequest {
    password!: string;
    name!: string;
    email!: string;
    picture!: string;
    gender!: EnumGender;

    constructor(data?: IAccountCreateRequest) {
        super(data);
    }

    init(data?: any) {
        super.init(data);
        if (data) {
            this.password = data["password"] !== undefined ? data["password"] : <any>null;
            this.name = data["name"] !== undefined ? data["name"] : <any>null;
            this.email = data["email"] !== undefined ? data["email"] : <any>null;
            this.picture = data["picture"] !== undefined ? data["picture"] : <any>null;
            this.gender = data["gender"] !== undefined ? data["gender"] : <any>null;
        }
    }

    static fromJS(data: any): AccountCreateRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AccountCreateRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["password"] = this.password !== undefined ? this.password : <any>null;
        data["name"] = this.name !== undefined ? this.name : <any>null;
        data["email"] = this.email !== undefined ? this.email : <any>null;
        data["picture"] = this.picture !== undefined ? this.picture : <any>null;
        data["gender"] = this.gender !== undefined ? this.gender : <any>null;
        super.toJSON(data);
        return data; 
    }
}

export interface IAccountCreateRequest extends IBaseDataTransfersOfAccountAndAccountCreateRequest {
    password: string;
    name: string;
    email: string;
    picture: string;
    gender: EnumGender;
}

export class AccountLoginResponse implements IAccountLoginResponse {
    token!: string;

    constructor(data?: IAccountLoginResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.token = data["token"] !== undefined ? data["token"] : <any>null;
        }
    }

    static fromJS(data: any): AccountLoginResponse {
        data = typeof data === 'object' ? data : {};
        let result = new AccountLoginResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["token"] = this.token !== undefined ? this.token : <any>null;
        return data; 
    }
}

export interface IAccountLoginResponse {
    token: string;
}

export class BaseDataTransfersOfAccountAndAccountLoginRequest implements IBaseDataTransfersOfAccountAndAccountLoginRequest {

    constructor(data?: IBaseDataTransfersOfAccountAndAccountLoginRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
    }

    static fromJS(data: any): BaseDataTransfersOfAccountAndAccountLoginRequest {
        data = typeof data === 'object' ? data : {};
        let result = new BaseDataTransfersOfAccountAndAccountLoginRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IBaseDataTransfersOfAccountAndAccountLoginRequest {
}

export class AccountLoginRequest extends BaseDataTransfersOfAccountAndAccountLoginRequest implements IAccountLoginRequest {
    email!: string;
    password!: string;

    constructor(data?: IAccountLoginRequest) {
        super(data);
    }

    init(data?: any) {
        super.init(data);
        if (data) {
            this.email = data["email"] !== undefined ? data["email"] : <any>null;
            this.password = data["password"] !== undefined ? data["password"] : <any>null;
        }
    }

    static fromJS(data: any): AccountLoginRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AccountLoginRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["email"] = this.email !== undefined ? this.email : <any>null;
        data["password"] = this.password !== undefined ? this.password : <any>null;
        super.toJSON(data);
        return data; 
    }
}

export interface IAccountLoginRequest extends IBaseDataTransfersOfAccountAndAccountLoginRequest {
    email: string;
    password: string;
}

export class BaseDataTransfersOfCommentAndCommentResponse implements IBaseDataTransfersOfCommentAndCommentResponse {

    constructor(data?: IBaseDataTransfersOfCommentAndCommentResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
    }

    static fromJS(data: any): BaseDataTransfersOfCommentAndCommentResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BaseDataTransfersOfCommentAndCommentResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IBaseDataTransfersOfCommentAndCommentResponse {
}

export class CommentResponse extends BaseDataTransfersOfCommentAndCommentResponse implements ICommentResponse {
    id!: number;
    content!: string;
    owner!: AccountSimpleResponse;
    post!: PostIdTransfer;
    created!: string;
    modified?: string | null;

    constructor(data?: ICommentResponse) {
        super(data);
        if (!data) {
            this.owner = new AccountSimpleResponse();
            this.post = new PostIdTransfer();
        }
    }

    init(data?: any) {
        super.init(data);
        if (data) {
            this.id = data["id"] !== undefined ? data["id"] : <any>null;
            this.content = data["content"] !== undefined ? data["content"] : <any>null;
            this.owner = data["owner"] ? AccountSimpleResponse.fromJS(data["owner"]) : new AccountSimpleResponse();
            this.post = data["post"] ? PostIdTransfer.fromJS(data["post"]) : new PostIdTransfer();
            this.created = data["created"] !== undefined ? data["created"] : <any>null;
            this.modified = data["modified"] !== undefined ? data["modified"] : <any>null;
        }
    }

    static fromJS(data: any): CommentResponse {
        data = typeof data === 'object' ? data : {};
        let result = new CommentResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id !== undefined ? this.id : <any>null;
        data["content"] = this.content !== undefined ? this.content : <any>null;
        data["owner"] = this.owner ? this.owner.toJSON() : <any>null;
        data["post"] = this.post ? this.post.toJSON() : <any>null;
        data["created"] = this.created !== undefined ? this.created : <any>null;
        data["modified"] = this.modified !== undefined ? this.modified : <any>null;
        super.toJSON(data);
        return data; 
    }
}

export interface ICommentResponse extends IBaseDataTransfersOfCommentAndCommentResponse {
    id: number;
    content: string;
    owner: AccountSimpleResponse;
    post: PostIdTransfer;
    created: string;
    modified?: string | null;
}

export class BaseDataTransfersOfPostAndPostIdTransfer implements IBaseDataTransfersOfPostAndPostIdTransfer {

    constructor(data?: IBaseDataTransfersOfPostAndPostIdTransfer) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
    }

    static fromJS(data: any): BaseDataTransfersOfPostAndPostIdTransfer {
        data = typeof data === 'object' ? data : {};
        let result = new BaseDataTransfersOfPostAndPostIdTransfer();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IBaseDataTransfersOfPostAndPostIdTransfer {
}

export class PostIdTransfer extends BaseDataTransfersOfPostAndPostIdTransfer implements IPostIdTransfer {
    id!: number;

    constructor(data?: IPostIdTransfer) {
        super(data);
    }

    init(data?: any) {
        super.init(data);
        if (data) {
            this.id = data["id"] !== undefined ? data["id"] : <any>null;
        }
    }

    static fromJS(data: any): PostIdTransfer {
        data = typeof data === 'object' ? data : {};
        let result = new PostIdTransfer();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id !== undefined ? this.id : <any>null;
        super.toJSON(data);
        return data; 
    }
}

export interface IPostIdTransfer extends IBaseDataTransfersOfPostAndPostIdTransfer {
    id: number;
}

export class BaseDataTransfersOfCommentAndCommentCreateRequest implements IBaseDataTransfersOfCommentAndCommentCreateRequest {

    constructor(data?: IBaseDataTransfersOfCommentAndCommentCreateRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
    }

    static fromJS(data: any): BaseDataTransfersOfCommentAndCommentCreateRequest {
        data = typeof data === 'object' ? data : {};
        let result = new BaseDataTransfersOfCommentAndCommentCreateRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IBaseDataTransfersOfCommentAndCommentCreateRequest {
}

export class CommentCreateRequest extends BaseDataTransfersOfCommentAndCommentCreateRequest implements ICommentCreateRequest {
    post!: PostIdTransfer;
    content!: string;

    constructor(data?: ICommentCreateRequest) {
        super(data);
        if (!data) {
            this.post = new PostIdTransfer();
        }
    }

    init(data?: any) {
        super.init(data);
        if (data) {
            this.post = data["post"] ? PostIdTransfer.fromJS(data["post"]) : new PostIdTransfer();
            this.content = data["content"] !== undefined ? data["content"] : <any>null;
        }
    }

    static fromJS(data: any): CommentCreateRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CommentCreateRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["post"] = this.post ? this.post.toJSON() : <any>null;
        data["content"] = this.content !== undefined ? this.content : <any>null;
        super.toJSON(data);
        return data; 
    }
}

export interface ICommentCreateRequest extends IBaseDataTransfersOfCommentAndCommentCreateRequest {
    post: PostIdTransfer;
    content: string;
}

export class BaseDataTransfersOfCommentAndCommentUpdateRequest implements IBaseDataTransfersOfCommentAndCommentUpdateRequest {

    constructor(data?: IBaseDataTransfersOfCommentAndCommentUpdateRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
    }

    static fromJS(data: any): BaseDataTransfersOfCommentAndCommentUpdateRequest {
        data = typeof data === 'object' ? data : {};
        let result = new BaseDataTransfersOfCommentAndCommentUpdateRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IBaseDataTransfersOfCommentAndCommentUpdateRequest {
}

export class CommentUpdateRequest extends BaseDataTransfersOfCommentAndCommentUpdateRequest implements ICommentUpdateRequest {
    id!: number;
    content!: string;

    constructor(data?: ICommentUpdateRequest) {
        super(data);
    }

    init(data?: any) {
        super.init(data);
        if (data) {
            this.id = data["id"] !== undefined ? data["id"] : <any>null;
            this.content = data["content"] !== undefined ? data["content"] : <any>null;
        }
    }

    static fromJS(data: any): CommentUpdateRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CommentUpdateRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id !== undefined ? this.id : <any>null;
        data["content"] = this.content !== undefined ? this.content : <any>null;
        super.toJSON(data);
        return data; 
    }
}

export interface ICommentUpdateRequest extends IBaseDataTransfersOfCommentAndCommentUpdateRequest {
    id: number;
    content: string;
}

export class BaseDataTransfersOfPostAndPostListResponse implements IBaseDataTransfersOfPostAndPostListResponse {

    constructor(data?: IBaseDataTransfersOfPostAndPostListResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
    }

    static fromJS(data: any): BaseDataTransfersOfPostAndPostListResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BaseDataTransfersOfPostAndPostListResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IBaseDataTransfersOfPostAndPostListResponse {
}

export class PostListResponse extends BaseDataTransfersOfPostAndPostListResponse implements IPostListResponse {
    id!: number;
    title!: string;
    cover!: string;
    content!: string;

    constructor(data?: IPostListResponse) {
        super(data);
    }

    init(data?: any) {
        super.init(data);
        if (data) {
            this.id = data["id"] !== undefined ? data["id"] : <any>null;
            this.title = data["title"] !== undefined ? data["title"] : <any>null;
            this.cover = data["cover"] !== undefined ? data["cover"] : <any>null;
            this.content = data["content"] !== undefined ? data["content"] : <any>null;
        }
    }

    static fromJS(data: any): PostListResponse {
        data = typeof data === 'object' ? data : {};
        let result = new PostListResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id !== undefined ? this.id : <any>null;
        data["title"] = this.title !== undefined ? this.title : <any>null;
        data["cover"] = this.cover !== undefined ? this.cover : <any>null;
        data["content"] = this.content !== undefined ? this.content : <any>null;
        super.toJSON(data);
        return data; 
    }
}

export interface IPostListResponse extends IBaseDataTransfersOfPostAndPostListResponse {
    id: number;
    title: string;
    cover: string;
    content: string;
}

export class BaseDataTransfersOfPostAndPostResponse implements IBaseDataTransfersOfPostAndPostResponse {

    constructor(data?: IBaseDataTransfersOfPostAndPostResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
    }

    static fromJS(data: any): BaseDataTransfersOfPostAndPostResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BaseDataTransfersOfPostAndPostResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IBaseDataTransfersOfPostAndPostResponse {
}

export class PostResponse extends BaseDataTransfersOfPostAndPostResponse implements IPostResponse {
    id!: number;
    title!: string;
    cover!: string;
    content!: string;
    owner!: AccountSimpleResponse;
    created!: string;
    modified?: string | null;
    comments!: CommentResponse[];

    constructor(data?: IPostResponse) {
        super(data);
        if (!data) {
            this.owner = new AccountSimpleResponse();
            this.comments = [];
        }
    }

    init(data?: any) {
        super.init(data);
        if (data) {
            this.id = data["id"] !== undefined ? data["id"] : <any>null;
            this.title = data["title"] !== undefined ? data["title"] : <any>null;
            this.cover = data["cover"] !== undefined ? data["cover"] : <any>null;
            this.content = data["content"] !== undefined ? data["content"] : <any>null;
            this.owner = data["owner"] ? AccountSimpleResponse.fromJS(data["owner"]) : new AccountSimpleResponse();
            this.created = data["created"] !== undefined ? data["created"] : <any>null;
            this.modified = data["modified"] !== undefined ? data["modified"] : <any>null;
            if (data["comments"] && data["comments"].constructor === Array) {
                this.comments = [] as any;
                for (let item of data["comments"])
                    this.comments!.push(CommentResponse.fromJS(item));
            }
        }
    }

    static fromJS(data: any): PostResponse {
        data = typeof data === 'object' ? data : {};
        let result = new PostResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id !== undefined ? this.id : <any>null;
        data["title"] = this.title !== undefined ? this.title : <any>null;
        data["cover"] = this.cover !== undefined ? this.cover : <any>null;
        data["content"] = this.content !== undefined ? this.content : <any>null;
        data["owner"] = this.owner ? this.owner.toJSON() : <any>null;
        data["created"] = this.created !== undefined ? this.created : <any>null;
        data["modified"] = this.modified !== undefined ? this.modified : <any>null;
        if (this.comments && this.comments.constructor === Array) {
            data["comments"] = [];
            for (let item of this.comments)
                data["comments"].push(item.toJSON());
        }
        super.toJSON(data);
        return data; 
    }
}

export interface IPostResponse extends IBaseDataTransfersOfPostAndPostResponse {
    id: number;
    title: string;
    cover: string;
    content: string;
    owner: AccountSimpleResponse;
    created: string;
    modified?: string | null;
    comments: CommentResponse[];
}

export class BaseDataTransfersOfPostAndPostCreateRequest implements IBaseDataTransfersOfPostAndPostCreateRequest {

    constructor(data?: IBaseDataTransfersOfPostAndPostCreateRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
    }

    static fromJS(data: any): BaseDataTransfersOfPostAndPostCreateRequest {
        data = typeof data === 'object' ? data : {};
        let result = new BaseDataTransfersOfPostAndPostCreateRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IBaseDataTransfersOfPostAndPostCreateRequest {
}

export class PostCreateRequest extends BaseDataTransfersOfPostAndPostCreateRequest implements IPostCreateRequest {
    title!: string;
    cover!: string;
    content!: string;

    constructor(data?: IPostCreateRequest) {
        super(data);
    }

    init(data?: any) {
        super.init(data);
        if (data) {
            this.title = data["title"] !== undefined ? data["title"] : <any>null;
            this.cover = data["cover"] !== undefined ? data["cover"] : <any>null;
            this.content = data["content"] !== undefined ? data["content"] : <any>null;
        }
    }

    static fromJS(data: any): PostCreateRequest {
        data = typeof data === 'object' ? data : {};
        let result = new PostCreateRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title !== undefined ? this.title : <any>null;
        data["cover"] = this.cover !== undefined ? this.cover : <any>null;
        data["content"] = this.content !== undefined ? this.content : <any>null;
        super.toJSON(data);
        return data; 
    }
}

export interface IPostCreateRequest extends IBaseDataTransfersOfPostAndPostCreateRequest {
    title: string;
    cover: string;
    content: string;
}

export class BaseDataTransfersOfPostAndPostUpdateRequest implements IBaseDataTransfersOfPostAndPostUpdateRequest {

    constructor(data?: IBaseDataTransfersOfPostAndPostUpdateRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
    }

    static fromJS(data: any): BaseDataTransfersOfPostAndPostUpdateRequest {
        data = typeof data === 'object' ? data : {};
        let result = new BaseDataTransfersOfPostAndPostUpdateRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data; 
    }
}

export interface IBaseDataTransfersOfPostAndPostUpdateRequest {
}

export class PostUpdateRequest extends BaseDataTransfersOfPostAndPostUpdateRequest implements IPostUpdateRequest {
    id!: number;
    title!: string;
    cover!: string;
    content!: string;

    constructor(data?: IPostUpdateRequest) {
        super(data);
    }

    init(data?: any) {
        super.init(data);
        if (data) {
            this.id = data["id"] !== undefined ? data["id"] : <any>null;
            this.title = data["title"] !== undefined ? data["title"] : <any>null;
            this.cover = data["cover"] !== undefined ? data["cover"] : <any>null;
            this.content = data["content"] !== undefined ? data["content"] : <any>null;
        }
    }

    static fromJS(data: any): PostUpdateRequest {
        data = typeof data === 'object' ? data : {};
        let result = new PostUpdateRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id !== undefined ? this.id : <any>null;
        data["title"] = this.title !== undefined ? this.title : <any>null;
        data["cover"] = this.cover !== undefined ? this.cover : <any>null;
        data["content"] = this.content !== undefined ? this.content : <any>null;
        super.toJSON(data);
        return data; 
    }
}

export interface IPostUpdateRequest extends IBaseDataTransfersOfPostAndPostUpdateRequest {
    id: number;
    title: string;
    cover: string;
    content: string;
}